---

# Останавливаем контейнер.
- name: Docker Update | Stop a container
  docker_container:
    name: "{{ deploy_name }}"
    state: stopped
    timeout: 600
  ignore_errors: yes

# Удаляем контейнер.
- name: Docker Update | Delete a container
  docker_container:
    name: "{{ deploy_name }}"
    state: absent
    timeout: 600
  ignore_errors: yes

# Создаём файл с переменными
- name: Docker Env | Configure env file
  template:
    src: "express.j2"
    dest: "{{ app_dir }}/.express-env"

# Создаём контейнер заново.
- name: Docker Update | Update a container
  docker_container:
    name: "{{ deploy_name }}"
    image: "{{ deploy_image }}"
    ports: "{{ deploy_ports }}"
    exposed_ports: "{{ deploy_exposed_ports }}"
    volumes: "{{ deploy_volumes }}"
    env_file: "{{ app_dir }}/.express-env"
    restart_policy: always
    state: started
    timeout: 600
