---

# Убиваем старую джобу
# Если старую джобу кильнуть не удалось, её нет, как при первом запуске, игнорим ошибки
- name: Update Spark | Kill old job
  shell: "./kill-job.sh {{ service_name }}.txt"
  args:
    chdir: "{{ app_dir }}/scripts/"
  ignore_errors: yes

# Ищем старые файлы
- name: Update Spark | Find old file .jar
  find:
    paths: "{{ app_dir }}/spark_data/"
    patterns: "^{{ service_name }}-*"
    file_type: "file"
    recurse: yes
    use_regex: yes
  register: artifact_name_old

# Удаляем старые файлы
- name: Update Spark | Remove old files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ artifact_name_old.files }}"

# Копируем новые файлы
- name: Update Spark | Copy new files
  copy:
    src: "{{ item }}"
    dest: "{{ app_dir }}/spark_data"
  with_fileglob:
    - "{{ path_to_artifacts }}/*"

# Ищем имя оставшегося файла и регистрируем его
- name: Update Spark | Find latest file .jar
  find:
    paths: "{{ app_dir }}/spark_data"
    patterns: "^{{ service_name }}-*"
    file_type: "file"
    use_regex: yes
  register: artifact_name

# Запускаем новую джобу
- name: Update Spark | Start new job
  shell: "./start-job.sh spark-worker-1 /opt/spark/spark_data/{{ artifact_name.files[0].path | basename }} {{ service_name }}.txt"
  args:
    chdir: "{{ app_dir }}/scripts/"
